[tool.black]
line-length = 88
target-version = ["py312"]  # Adjust if you are using Python 3.12

[tool.isort]
multi_line_output = 3
profile = "black"
src_paths = ["src", "test"]

[project]
name="src"
version = "0.1.0"
description = "Seg CT"
authors = [{email = "krishna.klume@gmail.com", name = "Keerthi Krishna P"}]
requires-python = ">=3.12"
readme = "README.md"

dependencies = [
    "numpy==1.26.4",
    "matplotlib==3.10.0",
    "pydantic>=2.10.6",
    "pymesh>=1.0.0",  # Fixed version specifier
    "meshio==5.3.5",
    "pygmsh==7.1.*",
    "gmsh==4.10.*",
    "scikit-image==0.25.2",
    "plotly==6.0.0",
    "scipy>=1.12.0",
    "shapely==2.0.6",
    "scipy >= 0.1.*",
    "streamlit >= 1.12.0",
    "streamlit-drawable-canvas  <= 0.9.*",
    "opencv-python >= 4.9.0",
    "pillow >= 10.0.0",
    "h5py >= 3.14.0"

]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
